#!/usr/bin/env python
"""Write the frontend's offline snapshot from whatever is currently in the DB.

    python seed.py --reset && python export_fallback.py

The dashboard reads this when the API is unreachable, so ``index.html`` renders
something real when opened straight off the filesystem. Regenerate it whenever
the response shape changes, or the offline view will quietly drift from the
live one.
"""

import argparse
import json
import sys
from pathlib import Path

from app.database import SessionLocal, init_db
from app.services import analytics

DEFAULT_OUT = Path(__file__).resolve().parent.parent / "frontend" / "fallback-data.js"

BANNER = """\
/* Auto-generated by backend/export_fallback.py — do not edit by hand.
 *
 * Offline snapshot rendered when the API at localhost:8000 is unreachable.
 * Regenerate with:  cd backend && python seed.py --reset && python export_fallback.py
 */
window.FINANCERT_FALLBACK = """


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    init_db()
    db = SessionLocal()
    try:
        overview = analytics.overview(db)
    finally:
        db.close()

    payload = json.loads(overview.model_dump_json())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(BANNER + json.dumps(payload, indent=2) + ";\n")

    print(f"Wrote {args.out} ({args.out.stat().st_size:,} bytes)")
    print(f"  {payload['total_positions']} positions, {len(payload['top_signals'])} signals")
    return 0


if __name__ == "__main__":
    sys.exit(main())
